{
	"schema_version": "1.6.0",
	"id": "BIT-gitlab-2023-3979",
	"modified": "2024-11-05T07:36:31.248Z",
	"published": "2024-03-06T11:01:15.790Z",
	"aliases": [
		"CVE-2023-3979"
	],
	"details": "An issue has been discovered in GitLab affecting all versions starting from 10.6 before 16.2.8, all versions starting from 16.3 before 16.3.5, all versions starting from 16.4 before 16.4.1. It was possible that upstream members to collaborate with you on your branch get permission to write to the merge requestâ€™s source branch. ",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "gitlab",
				"purl": "pkg:bitnami/gitlab"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "10.6.0"
						},
						{
							"fixed": "16.2.8"
						},
						{
							"introduced": "16.3.0"
						},
						{
							"fixed": "16.3.5"
						},
						{
							"introduced": "16.4.0"
						},
						{
							"fixed": "16.4.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/gitlab/BIT-gitlab-2023-3979.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://gitlab.com/gitlab-org/gitlab/-/issues/419972"
		},
		{
			"type": "WEB",
			"url": "https://hackerone.com/reports/2082560"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:16.4.0:*:*:*:community:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:16.4.0:*:*:*:enterprise:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*"
		],
		"severity": "Medium"
	}
}
