{
	"schema_version": "1.6.0",
	"id": "BIT-python-2023-38898",
	"modified": "2025-01-16T09:12:12.179905Z",
	"published": "2024-03-06T11:03:22.682Z",
	"aliases": [
		"BIT-python-2022-48566",
		"BIT-python-min-2022-48566",
		"CVE-2022-48566",
		"CVE-2023-38898",
		"GHSA-cgfh-jp5w-8cmx",
		"GHSA-crhm-wc96-7579",
		"PSF-2023-5",
		"PSF-2023-6",
		"PSF-2023-7"
	],
	"details": "An issue in Python cpython v.3.7 allows an attacker to obtain sensitive information via the _asyncio._swap_current_task component. NOTE: this is disputed by the vendor because (1) neither 3.7 nor any other release is affected (it is a bug in some 3.12 pre-releases); (2) there are no common scenarios in which an adversary can call _asyncio._swap_current_task but does not already have the ability to call arbitrary functions; and (3) there are no common scenarios in which sensitive information, which is not already accessible to an adversary, becomes accessible through this bug.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "python",
				"purl": "pkg:bitnami/python"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "3.13.0-alpha0"
						},
						{
							"last_affected": "3.13.0-alpha0"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/python/BIT-python-2023-38898.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://github.com/python/cpython/issues/105987"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:python:python:3.13.0:alpha0:*:*:*:*:*:*"
		],
		"severity": "Medium"
	}
}
