{
	"schema_version": "1.6.0",
	"id": "BIT-gitlab-2020-13336",
	"modified": "2024-11-27T19:40:48.342Z",
	"published": "2024-03-06T11:21:53.536Z",
	"aliases": [
		"CVE-2020-13336"
	],
	"details": "An issue has been discovered in GitLab affecting versions from 11.8 before 12.10.13. GitLab was vulnerable to a stored XSS by in the error tracking feature.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "gitlab",
				"purl": "pkg:bitnami/gitlab"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:H/PR:H/UI:R/S:C/C:L/I:L/A:N"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "11.8.0"
						},
						{
							"fixed": "12.10.13"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/gitlab/BIT-gitlab-2020-13336.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13336.json"
		},
		{
			"type": "WEB",
			"url": "https://gitlab.com/gitlab-org/gitlab/-/issues/215970"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*"
		],
		"severity": "Medium"
	}
}
