{
	"schema_version": "1.6.0",
	"id": "BIT-python-2022-48560",
	"modified": "2024-03-06T11:25:28.861Z",
	"published": "2024-03-06T11:04:43.366Z",
	"aliases": [
		"CVE-2022-48560",
		"GHSA-pvw5-cvp6-cv92",
		"PSF-2023-11"
	],
	"details": "A use-after-free exists in Python through 3.9 via heappushpop in heapq.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "python",
				"purl": "pkg:bitnami/python"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.11"
						},
						{
							"introduced": "3.7.0"
						},
						{
							"fixed": "3.7.7"
						},
						{
							"introduced": "3.8.0"
						},
						{
							"fixed": "3.8.2"
						}
					]
				},
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "3.9.0-alpha1"
						},
						{
							"last_affected": "3.9.0-alpha1"
						},
						{
							"introduced": "3.9.0-alpha2"
						},
						{
							"last_affected": "3.9.0-alpha2"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/python/BIT-python-2022-48560.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://bugs.python.org/issue39421"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html"
		},
		{
			"type": "WEB",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JZ5OOBWNYWXFTZDMCGHJVGDLDTHLWITJ/"
		},
		{
			"type": "WEB",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VO7Y2YZSDK3UYJD2KBGLXRTGNG6T326J/"
		},
		{
			"type": "WEB",
			"url": "https://security.netapp.com/advisory/ntap-20230929-0008/"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
			"cpe:2.3:a:python:python:3.9.0:alpha1:*:*:*:*:*:*",
			"cpe:2.3:a:python:python:3.9.0:alpha2:*:*:*:*:*:*"
		],
		"severity": "High"
	}
}
