{
	"schema_version": "1.6.0",
	"id": "BIT-python-min-2022-48566",
	"modified": "2025-01-16T09:12:12.179905Z",
	"published": "2025-01-16T07:21:47.986Z",
	"aliases": [
		"BIT-python-2022-48566",
		"BIT-python-2023-38898",
		"CVE-2022-48566",
		"CVE-2023-38898",
		"GHSA-cgfh-jp5w-8cmx",
		"GHSA-crhm-wc96-7579",
		"PSF-2023-5",
		"PSF-2023-6",
		"PSF-2023-7"
	],
	"details": "An issue was discovered in compare_digest in Lib/hmac.py in Python through 3.9.1. Constant-time-defeating optimisations were possible in the accumulator variable in hmac.compare_digest.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "python-min",
				"purl": "pkg:bitnami/python-min"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.13"
						},
						{
							"introduced": "3.7.0"
						},
						{
							"fixed": "3.7.10"
						},
						{
							"introduced": "3.8.0"
						},
						{
							"fixed": "3.8.7"
						},
						{
							"introduced": "3.9.0"
						},
						{
							"fixed": "3.9.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/python-min/BIT-python-min-2022-48566.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://bugs.python.org/issue40791"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html"
		},
		{
			"type": "WEB",
			"url": "https://security.netapp.com/advisory/ntap-20231006-0013/"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
		],
		"severity": "Medium"
	}
}
