{
	"schema_version": "1.6.0",
	"id": "BIT-tensorflow-2021-29563",
	"modified": "2024-03-06T11:25:28.861Z",
	"published": "2024-03-06T11:19:05.998Z",
	"aliases": [
		"CVE-2021-29563",
		"GHSA-ph87-fvjr-v33w",
		"PYSEC-2021-200",
		"PYSEC-2021-491",
		"PYSEC-2021-689"
	],
	"details": "TensorFlow is an end-to-end open source platform for machine learning. An attacker can cause a denial of service by exploiting a `CHECK`-failure coming from the implementation of `tf.raw_ops.RFFT`. Eigen code operating on an empty matrix can trigger on an assertion and will cause program termination. The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "tensorflow",
				"purl": "pkg:bitnami/tensorflow"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.1.4"
						},
						{
							"introduced": "2.2.0"
						},
						{
							"fixed": "2.2.3"
						},
						{
							"introduced": "2.3.0"
						},
						{
							"fixed": "2.3.3"
						},
						{
							"introduced": "2.4.0"
						},
						{
							"fixed": "2.4.2"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/tensorflow/BIT-tensorflow-2021-29563.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://github.com/tensorflow/tensorflow/commit/31bd5026304677faa8a0b77602c6154171b9aec1"
		},
		{
			"type": "WEB",
			"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-ph87-fvjr-v33w"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*"
		],
		"severity": "Medium"
	}
}
