{
	"schema_version": "1.6.0",
	"id": "BIT-pillow-2021-28675",
	"modified": "2024-03-06T11:25:28.861Z",
	"published": "2024-03-06T11:03:45.309Z",
	"aliases": [
		"CVE-2021-28675",
		"GHSA-g6rj-rv7j-xwp4",
		"PYSEC-2021-139"
	],
	"details": "An issue was discovered in Pillow before 8.2.0. PSDImagePlugin.PsdImageFile lacked a sanity check on the number of input layers relative to the size of the data block. This could lead to a DoS on Image.open prior to Image.load.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "pillow",
				"purl": "pkg:bitnami/pillow"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "8.2.0"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/pillow/BIT-pillow-2021-28675.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/"
		},
		{
			"type": "WEB",
			"url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28675-fix-dos-in-psdimageplugin"
		},
		{
			"type": "WEB",
			"url": "https://security.gentoo.org/glsa/202107-33"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:python:pillow:*:*:*:*:*:*:*:*"
		],
		"severity": "Medium"
	}
}
